name: post uni

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 1,4,7,10,13,16,19,22 * * *"
jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: set up environment variables
      run: |
        echo "BSKY_HANDLE=${{ secrets.BSKY_HANDLE }}" >> $GITHUB_ENV
        echo "BSKY_APP_PASSWORD=${{ secrets.BSKY_APP_PASSWORD }}" >> $GITHUB_ENV
    - name: install dependencies
      run: pip install atproto wand && sudo apt-get install imagemagick
    - name: post to bluesky
      # retries on fail
      # TODO: the action should fail if the command fails
      run: for i in {1..5}; do python uni.py && break || sleep 15; done 
    - name: update log
      uses: EndBug/add-and-commit@v9
      with:
        pull: "--rebase --autostash ."
        message: "[automated] rename image"
        default_author: github_actions
